version: '3'

services:
  web:
    build: .
    container_name: samuelclay-web
    # command: python manage.py runserver 0.0.0.0:8882
    command: ["gunicorn", "wsgi:application", "--bind", "0.0.0.0:8882"]
    volumes:
      - ${PWD}:/app
    ports:
      - "8882:8882"
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: samuelclay-nginx
    volumes:
      - ./config/nginx.prod:/etc/nginx/conf.d
      - ${PWD}/media:/static
      - ${PWD}/media:/media
      - certs:/etc/letsencrypt
    ports:
      - "8883:80" # For local dev
      - "8443:443" # For local dev
      # - "80:80"
      # - "443:443"
    depends_on:
      - web
      - certbot
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: samuelclay-certbot
    # Note: This container will exit after running, which is expected behavior
    # The renewal is handled by the renew-certbot-standalone.sh script
    command: certonly --standalone --preferred-challenges http --agree-tos --no-eff-email --keep-until-expiring --expand --email samuel@ofbrooklyn.com -d samuelclay.com -v
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot

volumes:
  certs:
  webroot:
